const API_URL = process.env.REACT_APP_API_URL || 'http://localhost:4000';
let authToken = localStorage.getItem('fx_token') || null;
export const setToken = (token) => { authToken = token; if (token) localStorage.setItem('fx_token', token); else localStorage.removeItem('fx_token'); };
export const getToken = () => authToken;
const apiFetch = async (endpoint, options = {}) => {
  const headers = { 'Content-Type': 'application/json', ...(authToken ? { Authorization: `Bearer ${authToken}` } : {}), ...options.headers };
  const res = await fetch(`${API_URL}${endpoint}`, { ...options, headers });
  if (res.status === 401) { setToken(null); window.location.reload(); throw new Error('Session expired'); }
  if (!res.ok) { const error = await res.json().catch(() => ({ error: 'Request failed' })); throw new Error(error.error || 'Request failed'); }
  return res.json();
};
export const apiLogin = async (email, password) => { const data = await apiFetch('/api/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); setToken(data.token); return data; };
export const logout = () => { setToken(null); localStorage.removeItem('fx_user'); };
export const getDashboardStats = () => apiFetch('/api/dashboard/stats');
export const getClients = (params = {}) => { const q = new URLSearchParams(params).toString(); return apiFetch(`/api/clients${q ? '?' + q : ''}`); };
export const createClient = (data) => apiFetch('/api/clients', { method: 'POST', body: JSON.stringify(data) });
export const updateClient = (id, data) => apiFetch(`/api/clients/${id}`, { method: 'PUT', body: JSON.stringify(data) });
export const getCandidates = (params = {}) => { const q = new URLSearchParams(params).toString(); return apiFetch(`/api/candidates${q ? '?' + q : ''}`); };
export const createCandidate = (data) => apiFetch('/api/candidates', { method: 'POST', body: JSON.stringify(data) });
export const updateCandidateStatus = (id, status, notes, jobId) => apiFetch(`/api/candidates/${id}/status`, { method: 'PUT', body: JSON.stringify({ status, notes, job_id: jobId }) });
export const getCandidateHistory = (id) => apiFetch(`/api/candidates/${id}/history`);
export const uploadCandidateWithCV = async (formData) => { const res = await fetch(`${API_URL}/api/candidates/upload-with-cv`, { method: 'POST', headers: { Authorization: `Bearer ${authToken}` }, body: formData }); if (!res.ok) throw new Error('Upload failed'); return res.json(); };
export const uploadCV = async (candidateId, file) => { const fd = new FormData(); fd.append('cv', file); const res = await fetch(`${API_URL}/api/candidates/${candidateId}/upload-cv`, { method: 'POST', headers: { Authorization: `Bearer ${authToken}` }, body: fd }); if (!res.ok) throw new Error('Upload failed'); return res.json(); };
export const getJobs = (params = {}) => { const q = new URLSearchParams(params).toString(); return apiFetch(`/api/jobs${q ? '?' + q : ''}`); };
export const getJob = (id) => apiFetch(`/api/jobs/${id}`);
export const createJob = (data) => apiFetch('/api/jobs', { method: 'POST', body: JSON.stringify(data) });
export const updateJob = (id, data) => apiFetch(`/api/jobs/${id}`, { method: 'PUT', body: JSON.stringify(data) });
export const getJobShareLinks = (id) => apiFetch(`/api/jobs/${id}/share`);
export const getPipeline = () => apiFetch('/api/pipeline');
export const moveStageAPI = (id, stage, notes) => apiFetch(`/api/pipeline/${id}/stage`, { method: 'PUT', body: JSON.stringify({ stage, notes }) });
export const getInterviews = (params = {}) => { const q = new URLSearchParams(params).toString(); return apiFetch(`/api/interviews${q ? '?' + q : ''}`); };
export const createInterview = (data) => apiFetch('/api/interviews', { method: 'POST', body: JSON.stringify(data) });
export const getWhatsAppThreads = () => apiFetch('/api/whatsapp/threads');
export const sendWhatsApp = (data) => apiFetch('/api/whatsapp/send', { method: 'POST', body: JSON.stringify(data) });
export const getTeam = () => apiFetch('/api/team');
export const getDailySourcing = (date) => apiFetch(`/api/reports/daily-sourcing?date=${date}`);
export const getDailyInterviews = (date) => apiFetch(`/api/reports/daily-interviews?date=${date}`);
export const getReportSummary = (period) => apiFetch(`/api/reports/summary?period=${period}`);
export const getRevenueReport = () => apiFetch('/api/reports/revenue');
export const checkHealth = () => apiFetch('/api/health');
